# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76b6140b769781c6d05b396c720456d585cfd4f2e52f666c9f73c74741650ec66cfffe9be2ca657aa381281e7e89189575334648a7cf7905b7efaac1d42fda22

test:
  secret_key_base: 22827978384e190aff7d91eaaa22827b2e8008bec047689ec4e5d29a0dfd605a39b4d6b649ab9976e64d5e4bcc674c44fa2d9fde25f62c4f0db65165447b2d60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
